### ISSUE TITLE
Hama ignoring TVDB main series posters

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#239]
Folder: Dokidoki Densetsu Mahoujin Guru Guru [anidb-1619]

This anime maps to season 2 on TVDB: https://www.thetvdb.com/series/magical-circle-guru-guru/seasons/2

Hama doesn't download the main anime posters on TVDB if there are no season posters on TVDB. All my posters come from other sources, despite TVDB having english main anime posters available to download.

> common.UpdateMeta() - fields in Metadata Sources per movie/serie, season, episodes
> - FanartTV         : posters                 (  1)
> - MyAnimeList      : genres                  (  7) | originally_available_at (  1) | title                   (  1) | summary                 (  1) | score                   (  1) | posters                 (  3)
> - TheTVDB          : status                  (  1) | rating                  (  1) | genres                  (  4) | art                     (  2) | roles                   ( 22) | originally_available_at (  1) | IMDbid                  (  1) | title                   (  1) | original_title          (  1) | language_rank           (  1) | studio                  (  1) | duration                (  1) | seasons                 (  1) | banners                 (  1) | Episodes  ( 38): duration                ( 38) | rating                  ( 38) | originally_available_at ( 38) | title                   ( 38)
> - AniDB            : status                  (  1) | rating                  (  1) | genres                  (  3) | roles                   ( 12) | originally_available_at (  1) | movie                   (  1) | title                   (  1) | original_title          (  1) | summary                 (  1) | language_rank           (  1) | seasons                 (  2) | duration                (  1) | posters                 (  1)
>   - Episodes  ( 39): duration                ( 39) | rating                  (  1) | title                   ( 39) | originally_available_at ( 39)
> - AnimeLists       : collection              (  1)

**Comment by ZeroQI** [comment]
Actually behaving as designed.  Some series have different posters for different seasons, like the monogataries series.
If you use AniDB numbering, then it will map to the season and take posters from it which in this case has none.

Maybe i can put a fail-over so that if no season posters exists, it takes the main series poster so that when a poster arrives for the season it will remove them... Will code tonight

**Comment by KurtzPT** [comment]
That would be the best design in my opinion, since TVDB posters are the best ones available (quality wise) and in most cases TVDB only has main serie posters and no season posters.

**Comment by KurtzPT** [comment]
I'm not sure why, but Hama is missing posters that are tagged as English. Using the same anime as above.

There are 4 main posters on TVDB, 2 of them are tagged as English which are the following:
- https://www.thetvdb.com/banners/posters/81095-4.jpg
- https://www.thetvdb.com/banners/posters/81095-3.jpg

These are the main anime posters that Hama downloads to plex:
![image](https://user-images.githubusercontent.com/14930057/43005598-41a441f0-8c2b-11e8-9f34-2c9473850aa0.png)

**It seems Hama is correctly identifying these posters:**

> ------------------------------
common.LoadFile() - file cached - CacheTime: 'Fri Jul 20 14:25:46 2018', Limit: 'Sat Jul 21 14:32:19 2018', url: 'https://api.thetvdb.com/series/81095/images/query?keyType=poster', Filename: 'TheTVDB/json/81095/images_poster_en.json' file_valid: 'True'
[!] bannerType: posters subKey:           rank:   7 filename: https://thetvdb.plexapp.com/banners/posters/81095-4.jpg thumbnail: https://thetvdb.plexapp.com/banners/_cache/posters/81095-4.jpg resolution: 680x1000 average: 10 count: 
[!] bannerType: posters subKey:           rank:   9 filename: https://thetvdb.plexapp.com/banners/posters/81095-3.jpg thumbnail: https://thetvdb.plexapp.com/banners/_cache/posters/81095-3.jpg resolution: 680x1000 average: 0 count: 
==========================
bannerTypes: {'fanart': 1, 'poster': 2, 'series': 2}, anidb_offset: 0, AniDBid: 1619, anidb_array: []
------------------------------
common.LoadFile() - file cached - CacheTime: 'Fri Jul 20 14:25:46 2018', Limit: 'Sat Jul 21 14:32:19 2018', url: 'https://api.thetvdb.com/series/81095/images/query?keyType=fanart', Filename: 'TheTVDB/json/81095/images_fanart_ja.json' file_valid: 'True'
[!] bannerType:     art subKey:      text rank:  28 filename: https://thetvdb.plexapp.com/banners/fanart/original/81095-1.jpg thumbnail: https://thetvdb.plexapp.com/banners/_cache/fanart/original/81095-1.jpg resolution: 1280x720 average: 6.5 count: 
------------------------------
common.LoadFile() - file cached - CacheTime: 'Fri Jul 20 14:25:47 2018', Limit: 'Sat Jul 21 14:32:19 2018', url: 'https://api.thetvdb.com/series/81095/images/query?keyType=poster', Filename: 'TheTVDB/json/81095/images_poster_ja.json' file_valid: 'True'
[!] bannerType: posters subKey:           rank:  27 filename: https://thetvdb.plexapp.com/banners/posters/81095-1.jpg thumbnail: https://thetvdb.plexapp.com/banners/_cache/posters/81095-1.jpg resolution: 680x1000 average: 0 count: 

**But later on the log there's no mention of actually adding these two TVDB posters:**

> common.UpdateMeta() - fields in Metadata Sources per movie/serie, season, episodes
 FanartTV         : posters                 (  1)
 MyAnimeList      : genres                  (  7) | originally_available_at (  1) | title                   (  1) | summary                 (  1) | score                   (  1) | posters                 (  3)
 TheTVDB          : status                  (  1) | rating                  (  1) | genres                  (  4) | art                     (  2) | roles                   ( 22) | originally_available_at (  1) | IMDbid                  (  1) | title                   (  1) | original_title          (  1) | language_rank           (  1) | studio                  (  1) | duration                (  1) | seasons                 (  1) | banners                 (  1)
   Episodes  ( 38): duration                ( 38) | rating                  ( 38) | originally_available_at ( 38) | title                   ( 38)
 AniDB            : status                  (  1) | rating                  (  1) | genres                  (  3) | roles                   ( 12) | originally_available_at (  1) | movie                   (  1) | title                   (  1) | original_title          (  1) | summary                 (  1) | language_rank           (  1) | seasons                 (  2) | duration                (  1) | posters                 (  1)
  Episodes  ( 39): duration                ( 39) | rating                  (  1) | title                   ( 39) | originally_available_at ( 39)
 AnimeLists       : collection              (  1)

**It then downloads two posters from other sources, the same ones in the image above:**

> [=] posters                  ( 1)  Sources: tvdb4, TheTVDB, TheMovieDb, (FanartTV), AniDB                 Inside: '['FanartTV', 'MyAnimeList', 'AniDB']'  Value: '{'https://assets.fanart.tv/fanart/tv/81095/tvposter/dokidoki-densetsu-mahoujin-guruguru-5575557af3dfb.jpg': ('FanartTV/tv/8109581095/tvposter/53284.jpg', 100, None)}'
[?] meta_new: {'http://img7.anidb.net/pics/anime/154141.jpg': ('AniDB/poster/154141.jpg', 25, 'http://img7.anidb.net/pics/anime/thumbs/150/154141.jpg-thumb.jpg')}, meta_old: ['https://assets.fanart.tv/fanart/tv/81095/tvposter/dokidoki-densetsu-mahoujin-guruguru-5575557af3dfb.jpg', 'http://img7.anidb.net/pics/anime/154141.jpg']
[=] posters                  ( 1)  Sources: tvdb4, TheTVDB, TheMovieDb, FanartTV, (AniDB)                 Inside: '['FanartTV', 'MyAnimeList', 'AniDB']'  Value: '{'http://img7.anidb.net/pics/anime/154141.jpg': ('AniDB/poster/154141.jpg', 25, 'http://img7.anidb.net/pics/anime/thumbs/150/154141.jpg-thumb.jpg')}'

Can you try and replicate @ZeroQI ?

**Comment by ZeroQI** [comment]
@KurtzPT so simple once solved. latest issue was solved with `not Dict(bannerTypes, 'season')` instead of `not Dict(bannerTypes, 'season')==0`

New code
```
              if bannerType=='season':  #tvdb season posters or anidb specials and defaulttvdb season  ## season 0 et empty+ season ==defaulttvdbseason(a=1)
                if not anidb_numbering:  SaveDict(('TheTVDB/'+image['fileName'], rank, thumbnail), TheTVDB_dict, 'seasons', str(image['subKey']), 'posters', TVDB_IMG_ROOT + image['fileName'])
                elif str(image['subKey'] or 0) in ('1' if Dict(mappingList, 'defaulttvdbseason')=='a' else (mappingList, 'defaulttvdbseason'), '0'):
                  SaveDict(('TheTVDB/'+image['fileName'], 1 if rank==3 else 3 if rank==1 else rank, thumbnail), TheTVDB_dict, 'seasons', '0' if str(image['subKey'])=='0' else '1' if anidb_numbering else str(image['subKey']), 'posters', TVDB_IMG_ROOT + image['fileName'])
                  SaveDict(('TheTVDB/'+image['fileName'], rank, thumbnail), TheTVDB_dict, 'posters', TVDB_IMG_ROOT + image['fileName'])
              elif bannerType=='fanart' or not anidb_numbering or Dict(mappingList, 'defaulttvdbseason') in ('a', '1') or str(image['subKey'] or '1')==Dict(mappingList, 'defaulttvdbseason') or not Dict(bannerTypes, 'season') and bannerType=='poster':
                SaveDict(('TheTVDB/'+image['fileName'], rank, thumbnail), TheTVDB_dict, metanames[bannerType], TVDB_IMG_ROOT + image['fileName'])   #use art + posters tvdb
```
Old code:
```
              if bannerType == 'season':  
                if anidb_numbering and ('1' if Dict(mappingList, 'defaulttvdbseason')=='a' else Dict(mappingList, 'defaulttvdbseason'))==str(image['subKey']):
                  SaveDict(('TheTVDB/'+image['fileName'], 1 if rank==3 else 3 if rank==1 else rank, thumbnail), TheTVDB_dict, 'seasons', '0' if str(image['subKey'])=='0' else '1', 'posters', TVDB_IMG_ROOT + image['fileName'])
                elif not anidb_numbering:  
                  season = str(int(image['subKey'])+(0 if Dict(mappingList, 'defaulttvdbseason')=="0" or not Dict(mappingList, 'defaulttvdbseason').isdigit() else int(Dict(mappingList, 'defaulttvdbseason'))-1))
                  SaveDict(   ('TheTVDB/'+image['fileName'], rank, thumbnail), TheTVDB_dict, 'seasons', season, 'posters', TVDB_IMG_ROOT + image['fileName'])
              if bannerType != 'season':
                SaveDict(('TheTVDB/'+image['fileName'], rank, thumbnail), TheTVDB_dict, metanames[bannerType],        TVDB_IMG_ROOT + image['fileName'])
```

**Comment by KurtzPT** [comment]
While it fixed the example I gave above, it's still not working 100%.

**Folder:** Fate Kaleid Liner Prisma Illya Zwei! [anidb-10091]
Inside I have the Episodes 1 to 10 and Specials 1 to 5.
**TVDB Link:** https://www.thetvdb.com/series/fate-kaleid-liner-prisma-illya
Episodes match to season 2 on TVDB
Specials match to special season on TVDB.
**My Poster Preferences:** language_posters:  ['en', 'ja']

**TVDB Posters:**
Special Season has one English poster and one Japanese poster:
- https://www.thetvdb.com/banners/seasons/269319-0-2.jpg 
- https://www.thetvdb.com/banners/seasons/269319-0.jpg
Season Two has one English poster:
- https://www.thetvdb.com/banners/seasons/269319-2-3.jpg
While Main Show has multiple English posters (not listing them here).

**This is what happens when Hama finishes downloading metadata:**
![image](https://user-images.githubusercontent.com/14930057/43039580-2e7e0fea-8d28-11e8-9196-0a3fae96a3dc.png)

**Going into detail:**
- All Main Series TVDB Posters are all missing from Plex, with Hama downloading all special season posters into it
- Specials Season is fine, all two posters are downloaded into it.
- Season Two (Season one in plex) is missing the only TVDB poster, so by default it uses the actual main serie poster like it can be seen in above image.

**Notes**
- I did notice the exact same behavior like my last comment here, TVDB loads the json files and sees all main series and season posters fine, but somewhere after this in the Hama logic things get totally wrong.
- In this case, plex main serie posters should not have the tvdb special posters in it, the season poster is missing and the tvdb main serie posters are missing from plex main serie posters.

**Comment by ZeroQI** [comment]
Please update and report, that should be it
- removed season poster as main poster for specials
- Missing 'Dict' dismissing anidb numbered series season poster

**Comment by KurtzPT** [comment]
Just tested, it did download the season 2 poster into main serie posters and season one plex posters.

Just to make sure, in case a season has TVDB posters, Hama won't download TVDB main serie posters into plex main serie posters?

**Comment by KurtzPT** [comment]
Didn't test much, but the anime above is fixed, it gets the main serie posters now. I'll try and test more tomorrow

**Comment by ZeroQI** [comment]
thanks. think we are there now.
btw, trying to write  new agent to save posters locally and themes
regardless of agent used
